'use client';

import React from "react";
import { 
  ClipboardCheck, 
  CheckCircle2, 
  Zap, 
  ArrowRight, 
  ShieldCheck, 
  Users, 
  Banknote, 
  FileText,
  Clock,
  Layout,
  MessageCircle,
  TrendingUp,
  Cpu
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ScrollReveal } from "@/components/animations/ScrollReveal";
import { ServiceHero } from "@/components/sections/ServiceHero";
import { ServiceFAQ } from "@/components/sections/ServiceFAQ";
import { CTASection } from "@/components/sections/CTASection";

export default function NetMeteringAssistancePage() {
  const supportItems = [
    { icon: <ShieldCheck />, title: "Eligibility guidance" },
    { icon: <FileText />, title: "Required document checklist" },
    { icon: <Layout />, title: "Application assistance" },
    { icon: <Users />, title: "DISCOM coordination" },
    { icon: <Cpu />, title: "Technical feasibility" },
    { icon: <Zap />, title: "Meter installation support" },
    { icon: <Clock />, title: "Approval follow-up" },
    { icon: <CheckCircle2 />, title: "Commissioning assistance" },
  ];

  const whoCanApply = [
    "Residential homeowners",
    "Commercial buildings",
    "Shops and offices",
    "Schools and institutions",
    "Industrial units",
    "Rooftop solar users",
    "PM Surya Ghar applicants",
  ];

  const benefits = [
    { title: "Reduce electricity bills", desc: "Offset your consumption with exported units." },
    { title: "Export extra units", desc: "Send surplus energy back to the grid for credits." },
    { title: "Improve ROI", desc: "Shorten the payback period of your solar investment." },
    { title: "Energy Efficiency", desc: "Better utilization of your rooftop solar potential." },
    { title: "Clean Energy Support", desc: "Contribute to a greener grid in Chhattisgarh." },
    { title: "Long-term savings", desc: "Locks in energy benefits for the next 25 years." },
  ];

  const steps = [
    { title: "Site & bill assessment", desc: "We analyze your roof and current consumption." },
    { title: "Document collection", desc: "Gathering required DISCOM paperwork." },
    { title: "Application submission", desc: "Filing through portal or office." },
    { title: "DISCOM review", desc: "Technical verification by board." },
    { title: "Technical approval", desc: "Feasibility clearance received." },
    { title: "Meter installation", desc: "Synchronization of solar meter." },
    { title: "Solar export starts", desc: "Savings reflected in next bill." },
  ];

  const faqs = [
    {
      question: "What is net metering in solar?",
      answer: "Net metering is a billing system where excess solar electricity generated by your rooftop solar system is exported to the grid and adjusted against your electricity bill."
    },
    {
      question: "Who can apply for net metering in Chhattisgarh?",
      answer: "Residential, commercial, institutional, and industrial solar users can apply for net metering, subject to DISCOM rules and technical approval."
    },
    {
      question: "Does SKY RENEWABLE help with net metering applications?",
      answer: "Yes, SKY RENEWABLE provides complete support for documentation, application submission, DISCOM coordination, approval follow-up, and meter installation guidance."
    },
    {
      question: "Is net metering required for PM Surya Ghar Yojana?",
      answer: "Yes, for grid-connected rooftop solar systems under PM Surya Ghar Yojana, net metering is generally required to track import and export of electricity."
    },
    {
      question: "How long does the net metering approval process take?",
      answer: "The timeline depends on document completion, DISCOM verification, and technical approval. SKY RENEWABLE helps customers complete the process as smoothly as possible."
    }
  ];

  return (
    <div className="bg-white overflow-hidden selection:bg-primary/20 selection:text-primary">
      <ServiceHero 
        badge="NET METERING SUPPORT"
        titleLine1="Net Metering Assistance"
        titleLine2="Save More With Export Benefits"
        description="SKY RENEWABLE helps residential, commercial, and industrial solar customers complete the net metering process smoothly. From documentation and application submission to approval coordination and meter installation support, our team guides you at every step."
        image="/servie/1.png"
        primaryButtonText="Apply for Net Metering"
        secondaryButtonText="Talk to Solar Expert"
      />

      {/* SECTION 1: WHAT IS NET METERING */}
      <section className="py-24 bg-[#F8FAFC]">
        <div className="container mx-auto px-4 max-w-4xl text-center">
          <ScrollReveal direction="up" className="space-y-6">
            <h2 className="text-[30px] lg:text-[40px] font-bold text-[#0F172A]">What is Net Metering?</h2>
            <p className="text-[16px] md:text-[18px] text-[#64748B] leading-relaxed">
              Net metering allows solar users to export excess electricity generated by their rooftop solar system back to the grid. The exported units are adjusted against your electricity bill, helping you reduce monthly power expenses and maximize solar savings.
            </p>
          </ScrollReveal>
        </div>
      </section>

      {/* SECTION 2: SUPPORT INCLUDES */}
      <section className="py-24 bg-white">
        <div className="container mx-auto px-4">
          <ScrollReveal direction="up" className="text-center mb-16">
            <h2 className="text-[30px] lg:text-[40px] font-bold text-[#0F172A]">Our Support Includes</h2>
          </ScrollReveal>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {supportItems.map((item, i) => (
              <ScrollReveal key={i} delay={i * 0.05} direction="up">
                <Card className="p-6 md:p-8 h-full rounded-[32px] border-none bg-[#F8FAFC] shadow-sm flex flex-col items-center text-center space-y-4 hover:shadow-md transition-all">
                  <div className="size-12 bg-[#EEF7FF] rounded-xl flex items-center justify-center text-[#2563EB]">
                    {React.cloneElement(item.icon as React.ReactElement, { className: "size-6" })}
                  </div>
                  <h3 className="text-sm md:text-base font-bold text-[#0F172A] leading-tight">{item.title}</h3>
                </Card>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 3 & 4: WHO CAN APPLY & DOCUMENTS */}
      <section className="py-24 bg-[#F8FAFC]">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-16">
            <ScrollReveal direction="right" className="space-y-8">
              <h2 className="text-[30px] lg:text-[40px] font-bold text-[#0F172A]">Who Can Apply?</h2>
              <div className="grid gap-3">
                {whoCanApply.map((item, i) => (
                  <div key={i} className="flex items-center gap-3 p-4 bg-white rounded-2xl border border-[#E2E8F0]">
                    <CheckCircle2 className="size-5 text-[#22C55E] shrink-0" />
                    <span className="text-[15px] font-bold text-[#0F172A]">{item}</span>
                  </div>
                ))}
              </div>
            </ScrollReveal>
            <ScrollReveal direction="left" className="space-y-8">
              <h2 className="text-[30px] lg:text-[40px] font-bold text-[#0F172A]">Required Documents</h2>
              <ul className="space-y-4">
                {[
                  "Electricity bill (Latest)",
                  "Consumer number / BP Number",
                  "Aadhaar & PAN card details",
                  "Property ownership / Rent proof",
                  "Solar system technical details",
                  "Registered installer details",
                  "Bank details & Cancelled cheque",
                  "Passport-size photo"
                ].map((doc, i) => (
                  <li key={i} className="flex items-center gap-4 text-[#64748B] text-[15px] font-medium border-b border-black/5 pb-2">
                    <div className="size-2 bg-[#2563EB] rounded-full shrink-0" />
                    {doc}
                  </li>
                ))}
              </ul>
            </ScrollReveal>
          </div>
        </div>
      </section>

      {/* SECTION 5: BENEFITS */}
      <section className="py-24 bg-white">
        <div className="container mx-auto px-4">
          <ScrollReveal direction="up" className="text-center mb-16">
            <h2 className="text-[30px] lg:text-[40px] font-bold text-[#0F172A]">Benefits of Net Metering</h2>
          </ScrollReveal>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {benefits.map((benefit, i) => (
              <ScrollReveal key={i} delay={i * 0.1} direction="up">
                <Card className="p-10 h-full rounded-[40px] border-none bg-[#F8FAFC] shadow-sm hover:shadow-xl transition-all group">
                  <div className="size-12 rounded-full bg-[#EEF7FF] text-[#2563EB] flex items-center justify-center mb-6 group-hover:bg-[rgba(255,152,0,0.12)] group-hover:text-[#FF9800] transition-colors">
                    <TrendingUp className="size-6" />
                  </div>
                  <h3 className="text-xl font-bold text-[#0F172A] mb-3">{benefit.title}</h3>
                  <p className="text-[14px] text-[#64748B] leading-relaxed">{benefit.desc}</p>
                </Card>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 6: PROCESS TIMELINE */}
      <section className="py-24 bg-[#0F172A] text-white">
        <div className="container mx-auto px-4">
          <ScrollReveal direction="up" className="text-center mb-20">
            <h2 className="text-[30px] lg:text-[40px] font-bold tracking-tight">Process Timeline</h2>
          </ScrollReveal>
          <div className="grid md:grid-cols-4 lg:grid-cols-7 gap-8">
            {steps.map((step, i) => (
              <ScrollReveal key={i} delay={i * 0.1} direction="up" className="space-y-4 text-center">
                <div className="text-[40px] md:text-[48px] font-bold text-white/10 leading-none">0{i + 1}</div>
                <h4 className="text-[13px] font-bold uppercase tracking-widest text-[#2563EB]">{step.title}</h4>
                <p className="text-[12px] text-white/60 leading-relaxed">{step.desc}</p>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 7: WHY CHOOSE */}
      <section className="py-24 bg-white">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div className="space-y-8">
              <ScrollReveal direction="right">
                <h2 className="text-[30px] lg:text-[40px] font-bold text-[#0F172A]">Why Choose SKY RENEWABLE?</h2>
                <div className="grid gap-4 mt-8">
                  {[
                    "CSPDCL registered vendor support",
                    "Experienced solar professionals",
                    "End-to-end guidance",
                    "Fast documentation support",
                    "Local Chhattisgarh service coverage",
                    "Residential and commercial expertise",
                    "Dedicated after-sales assistance"
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-4 p-5 bg-[#F8FAFC] rounded-3xl border border-[#E2E8F0]">
                      <CheckCircle2 className="size-5 text-[#22C55E] shrink-0" />
                      <span className="text-[15px] font-bold text-[#0F172A]">{item}</span>
                    </div>
                  ))}
                </div>
              </ScrollReveal>
            </div>
            <ScrollReveal direction="left">
               <div className="relative aspect-[4/3] rounded-[40px] overflow-hidden shadow-2xl">
                 <img 
                   src="/servie/7.png" 
                   alt="Net Metering Support" 
                   className="object-cover w-full h-full"
                 />
               </div>
            </ScrollReveal>
          </div>
        </div>
      </section>

      <ServiceFAQ serviceName="Net Metering Assistance" faqs={faqs} />

      {/* FINAL CTA */}
      <section className="py-24 px-4 bg-white">
        <div className="container mx-auto max-w-5xl text-center">
          <div className="relative overflow-hidden rounded-[48px] bg-[#0F172A] px-8 py-20 shadow-2xl">
            <div className="relative z-10 space-y-8">
              <h2 className="text-[32px] md:text-[48px] font-bold text-white tracking-tight">
                Start Net Metering With Expert Support
              </h2>
              <p className="text-white/70 text-lg max-w-2xl mx-auto">
                Make your solar system more rewarding with professional net metering assistance from SKY RENEWABLE.
              </p>
              <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                <Button asChild size="lg" className="bg-primary text-white rounded-full px-10 h-14 font-bold text-[15px] hover:bg-primary/90 transition-all w-full sm:w-auto">
                  <a href="/get-quote">Get Free Consultation</a>
                </Button>
                <Button asChild variant="outline" size="lg" className="bg-[#22C55E] border-none text-white rounded-full px-10 h-14 font-bold text-[15px] hover:bg-[#1BA850] transition-all w-full sm:w-auto">
                  <a href="https://wa.me/918871105807" target="_blank">
                    <MessageCircle className="size-5 mr-2" /> WhatsApp Now
                  </a>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
